name: Test API
run-name: API Test by ${{github.actor}}
on: [push]
jobs:
  Run-API:
    runs-on: ubuntu-latest
    steps:
      - name: Job details
        run: |
          echo "Current job is running on ${{runner.os}} hosted at GitHub"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Cloning code into the Job
        uses: actions/checkout@v4

      - name: Starting the services
        run: |
          touch .env
          cat example.env > .env
          docker compose up -d
          echo "Services are running"
          
      - name: Wait for API to be ready
        run: |
          until curl -s http://localhost:4000/api/health; do
            echo "Waiting for API to start..."
            sleep 10  # Adjust the sleep time based on the startup time of your API
          done

      - name: API health check
        run: |
          docker ps
          # curl -X GET 'http://host.docker.internal:4000/api/health' -H 'accept: application/json' -H 'Authorization: Bearer cdhub-api-key-123' 
      - name: Job status
        run: echo "${{job.status}}"
